Algoritmo "visualg043ex3"
//Desenvolver um programa que apresente o fatorial de um
//número qualquer

Var
// Seção de Declarações das variáveis 
 n , contador, acumulador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
acumulador <- 1

escreval("Me informe um número qualquer :")
leia(n)

para contador de 1 ate n passo 1 faca
       acumulador <- acumulador * 1
fimpara
escreval ("O fatorial do número  ", n ," é ", acumulador)

Fimalgoritmo